"""Isoform Explorer — Streamlit page.

Browse the exon/isoform architecture of any gene, inspect whether a
constitutive sequence exists, and download the N-collapsed FASTA as input
to the smFISH / HCR probe designer.

Self-contained: does not touch the probe-design code paths.
Data: Ensembl v113, generated by docs/HCR_plan/isoform_explorer/export_to_parquet.R.
"""
from __future__ import annotations

import matplotlib.pyplot as plt
import pandas as pd
import streamlit as st

from isoform_data import (
    SPECIES_LABELS,
    get_gene_intervals,
    get_gene_record,
    load_species_metadata,
    plot_isoforms,
    safe_tsl_label,
)

# ── Sidebar ───────────────────────────────────────────────────────────────────

st.sidebar.header("Isoform Explorer")

species_key = st.sidebar.selectbox(
    "Species",
    options=list(SPECIES_LABELS.keys()),
    format_func=lambda k: SPECIES_LABELS[k],
)

# Light read: gene_id, gene_name, constitutive_length, constitutive_exist
meta_df = load_species_metadata(species_key)

# Text filter to keep the dropdown manageable (~55k options for human)
search_text = st.sidebar.text_input(
    "Search gene",
    placeholder="type gene name or Ensembl ID…",
)

if search_text.strip():
    q = search_text.strip().lower()
    mask = (
        meta_df["gene_id"].str.lower().str.contains(q, na=False)
        | meta_df["gene_name"].str.lower().str.contains(q, na=False)
    )
    filtered_df = meta_df[mask]
else:
    filtered_df = meta_df

gene_id: str | None = None

if filtered_df.empty:
    st.sidebar.warning("No genes match the search.")
else:
    n_matches = len(filtered_df)
    label_map = {
        row["gene_id"]: f"{row['gene_name']}  —  {row['gene_id']}"
        for _, row in filtered_df.iterrows()
    }
    gene_id = st.sidebar.selectbox(
        f"Gene  ({n_matches:,} match{'es' if n_matches != 1 else ''})",
        options=filtered_df["gene_id"].tolist(),
        format_func=lambda k: label_map[k],
    )

# ── Main panel ────────────────────────────────────────────────────────────────

st.title("Isoform Explorer")
st.caption(
    "Browse the isoform architecture of any gene and export its "
    "**constitutive sequence** — the region shared by all isoforms — "
    "as a FASTA file for smFISH / HCR probe design. "
    "Data: Ensembl v113 · TSL adaptive filtering applied to Hsap / Mmus."
)
st.divider()

if gene_id is None:
    st.info("Select a species and search for a gene in the sidebar to get started.")
    st.stop()

# ── Load data ─────────────────────────────────────────────────────────────────

record      = get_gene_record(species_key, gene_id)
intervals_df = get_gene_intervals(species_key, gene_id)

gene_name   = str(record["gene_name"])
strand      = str(record["strand"])
biotype     = str(record["gene_biotype"])
const_exist = bool(record["constitutive_exist"])
const_len   = int(record["constitutive_length"])
tsl_cutoff  = str(record["tsl_cutoff"])
n_isoforms  = int(record["isoform_count"])

# ── Isoform structure plot ────────────────────────────────────────────────────

with st.spinner("Rendering isoform structure…"):
    fig = plot_isoforms(intervals_df, record)

st.pyplot(fig, use_container_width=True)
plt.close(fig)

# ── Gene summary (compact) ────────────────────────────────────────────────────

st.markdown(
    f"**{gene_name}** &nbsp;·&nbsp; {biotype} &nbsp;·&nbsp; {strand} strand "
    f"&nbsp;·&nbsp; {n_isoforms} isoform{'s' if n_isoforms != 1 else ''} &nbsp;·&nbsp; "
    f"filter: {tsl_cutoff} &nbsp;·&nbsp; Ensembl v113"
)

# ── Constitutive sequence status ──────────────────────────────────────────────

if not const_exist:
    st.warning(
        "**No constitutive sequence** — this gene has no region shared by all isoforms. "
        "Inspect the plot above and consider targeting a MANE / reference isoform instead.",
        icon="⚠️",
    )
elif const_len < 500:
    st.warning(
        f"**Short constitutive sequence ({const_len:,} nt)** — this may not accommodate "
        "enough probes. Consider using a MANE / reference isoform.",
        icon="⚠️",
    )
else:
    st.success(
        f"**Constitutive sequence: {const_len:,} nt** — suitable for smFISH / HCR probe design.",
        icon="✅",
    )

# ── Sequence display and download ─────────────────────────────────────────────

if const_exist:
    import textwrap

    seq = str(record["constitutive_seq_Ncollapsed"])
    fasta_header  = f">{gene_id}_{gene_name} constitutive_seq_Ncollapsed Ensembl_v113 filter_{safe_tsl_label(tsl_cutoff)}"
    fasta_seq     = textwrap.fill(seq, width=80)
    fasta_text    = f"{fasta_header}\n{fasta_seq}\n"
    filename      = f"{gene_name}_{gene_id}_constitutive.fa"

    with st.expander("Constitutive sequence (N-collapsed)", expanded=True):
        st.caption(
            "↗ Use the copy button at the top-right of the box to copy, or download the FASTA below. "
            "Paste directly into the smFISH / HCR probe designer."
        )
        st.code(fasta_text, language=None)

    st.download_button(
        label="⬇ Download FASTA",
        data=fasta_text,
        file_name=filename,
        mime="text/plain",
        type="primary",
        use_container_width=False,
    )
